[package]
name = "passgone"
version = "0.3.0"
edition = "2021"

[dependencies]
anyhow = "1.0.75"
argon2 = { version = "0.5.2", features = ["zeroize"] }
clap = { version = "4.4.6", features = ["derive"] }
rpassword = "7.2.0"
scopeguard = "1.2.0"
thiserror = "1.0.49"
zeroize = "1.6.0"
