name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  fmt-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Check code formatting
      run: cargo fmt --check

  clippy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run clippy
      run: cargo clippy --verbose

  test-vectors:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run test vectors
      run: cargo test --verbose --release --features test-vectors
